name: screenshots
on:
  push:
    branches:
      - main
      - mrc-4306
jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Run WODIN
        run: ./scripts/run-wodin
      - name: Run Playwright suite
        run: |
          cd screenshot
          npm install -D @playwright/test && npx playwright install
          npx playwright test
      - uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: screenshot/screenshots/